import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Terms of Service",
}

export default function TermsPage() {
  return (
    <div className="px-4 py-16 sm:px-6 sm:py-20">
      <div className="mx-auto max-w-[65ch]">
        <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">Terms of Service</h1>
        <p className="mt-2 text-sm text-muted-foreground">Last updated 5 July 2026</p>

        <div className="prose-sarathi prose mt-10 max-w-none dark:prose-invert">
          <p>
            These terms cover your use of Sarathi, a project built by Nihesh Rachakonda for a
            banking hackathon. Please read them - they are short, and written to be honest
            about exactly what this product is and isn&apos;t.
          </p>

          <h2>1. What Sarathi is</h2>
          <p>
            Sarathi is a hackathon prototype that demonstrates agentic AI banking - a
            conversational assistant that can open accounts, notice life events, and suggest
            products, all through chat. It is a technology demonstration, not a bank. Sarathi is
            not a licensed banking, payments, or financial services provider in India or
            anywhere else, and it is not affiliated with, endorsed by, or operated on behalf of
            the State Bank of India or any other financial institution. Nothing you see here is
            covered by any deposit insurance scheme, and no real money ever moves through it.
          </p>

          <h2>2. Synthetic data, not your real finances</h2>
          <p>
            Every account, balance, transaction, and holding shown inside Sarathi is synthetic -
            produced by a simulation engine purely for demonstration. Tapping &quot;Load demo
            activity&quot; asks that engine to fabricate a plausible transaction history so you
            can see the dashboard, nudges, and chat working end to end. None of it reads from or
            writes to any real bank account, card, or payment network. Please don&apos;t enter
            real account numbers, card numbers, government identifiers, or other sensitive
            financial details into the chat - there is no reason to, since no real banking
            system ever sees them.
          </p>

          <h2>3. Your account</h2>
          <p>
            You sign in with Google OAuth, a passkey, or a one-time email code. Whichever
            identity you provide is used to create a lightweight profile so your chat history,
            nudges, and dashboard persist between visits. You&apos;re responsible for keeping
            your sign-in method secure - if you register a passkey, keep control of the device
            or authenticator that holds it.
          </p>

          <h2>4. Acceptable use</h2>
          <p>
            Use Sarathi to explore the product, not to attack it. Don&apos;t try to bypass
            authentication, scrape the API outside normal use, send prompts designed to
            exfiltrate other users&apos; data, or use the service for anything unlawful. We may
            suspend or remove access for accounts that abuse the service.
          </p>

          <h2>5. AI-generated content</h2>
          <p>
            Sarathi&apos;s replies are generated by large language models and should be treated
            as illustrative, not as financial, legal, or tax advice. Model output can be
            incomplete, wrong, or strangely phrased even when the underlying data is synthetic -
            don&apos;t rely on anything Sarathi says as real financial guidance.
          </p>

          <h2>6. No warranty</h2>
          <p>
            Sarathi is provided &quot;as is,&quot; as a prototype, with no uptime guarantee and
            no warranty of merchantability or fitness for a particular purpose. To the fullest
            extent the law allows, Nihesh Rachakonda is not liable for any damages arising from
            your use of, or inability to use, this prototype.
          </p>

          <h2>7. Changes</h2>
          <p>
            This is an actively developed prototype - features, copy, and these terms may change
            without notice. Continuing to use Sarathi after a change means you accept the
            updated terms.
          </p>

          <h2>8. Governing law</h2>
          <p>
            These terms are governed by the laws of India, without regard to conflict-of-law
            principles. Any dispute arising from your use of Sarathi is subject to the exclusive
            jurisdiction of the courts of India.
          </p>

          <h2>9. Contact</h2>
          <p>
            Questions about these terms, or anything else about Sarathi? Write to{" "}
            <a href="mailto:niheshr03@gmail.com">niheshr03@gmail.com</a>.
          </p>
        </div>
      </div>
    </div>
  )
}
