"""add handoff requests table

Revision ID: 80916cd8d4fc
Revises: e1eeaf270f91
Create Date: 2026-07-05 06:25:42.389567

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '80916cd8d4fc'
down_revision: str | None = 'e1eeaf270f91'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handoff_requests',
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('urgency', sa.Enum('low', 'normal', 'high', name='handoffurgency', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('open', 'claimed', 'resolved', name='handoffstatus', native_enum=False, length=32), nullable=False),
    sa.Column('claimed_by', sa.String(length=320), nullable=True),
    sa.Column('resolution_note', sa.String(length=1000), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_handoff_requests_conversation', 'handoff_requests', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_handoff_requests_customer_id'), 'handoff_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_handoff_requests_status'), 'handoff_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_handoff_requests_status'), table_name='handoff_requests')
    op.drop_index(op.f('ix_handoff_requests_customer_id'), table_name='handoff_requests')
    op.drop_index('ix_handoff_requests_conversation', table_name='handoff_requests')
    op.drop_table('handoff_requests')
    # ### end Alembic commands ###
