"""add customer preferred_language

Revision ID: 983def1dec81
Revises: f74e44645e6c
Create Date: 2026-07-05 03:30:40.009986

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '983def1dec81'
down_revision: str | None = 'f74e44645e6c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('preferred_language', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'preferred_language')
    # ### end Alembic commands ###
