"""add transaction event_id

Revision ID: a731a75df0ba
Revises: 6b09b7005a82
Create Date: 2026-07-04 13:17:08.076123

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'a731a75df0ba'
down_revision: str | None = '6b09b7005a82'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('event_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_transactions_event_id', 'transactions', ['event_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_event_id', 'transactions', type_='unique')
    op.drop_column('transactions', 'event_id')
    # ### end Alembic commands ###
