"""add staff notes table

Revision ID: b76c9c475c2a
Revises: e56ffc834635
Create Date: 2026-07-05 05:29:30.105418

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b76c9c475c2a'
down_revision: str | None = 'e56ffc834635'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_notes',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('author_email', sa.String(length=320), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_staff_notes_customer_created', 'staff_notes', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_staff_notes_customer_id'), 'staff_notes', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_notes_customer_id'), table_name='staff_notes')
    op.drop_index('ix_staff_notes_customer_created', table_name='staff_notes')
    op.drop_table('staff_notes')
    # ### end Alembic commands ###
