"""add savings goals

Revision ID: e1eeaf270f91
Revises: b76c9c475c2a
Create Date: 2026-07-05 05:57:27.896760

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e1eeaf270f91'
down_revision: str | None = 'b76c9c475c2a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings_goals',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('target_paise', sa.BigInteger(), nullable=False),
    sa.Column('baseline_paise', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'achieved', 'archived', name='goalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('achieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_paise > 0', name='ck_savings_goals_target_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_savings_goals_customer_created', 'savings_goals', ['customer_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_savings_goals_customer_id'), 'savings_goals', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_goals_customer_id'), table_name='savings_goals')
    op.drop_index('ix_savings_goals_customer_created', table_name='savings_goals')
    op.drop_table('savings_goals')
    # ### end Alembic commands ###
