"""add sim_injections table

Revision ID: e56ffc834635
Revises: 983def1dec81
Create Date: 2026-07-05 03:37:41.305867

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e56ffc834635'
down_revision: str | None = '983def1dec81'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sim_injections',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('injected_type', sa.String(length=40), nullable=False),
    sa.Column('injected_by', sa.String(length=120), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('injected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sim_injections_customer_id'), 'sim_injections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sim_injections_injected_at'), 'sim_injections', ['injected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sim_injections_injected_at'), table_name='sim_injections')
    op.drop_index(op.f('ix_sim_injections_customer_id'), table_name='sim_injections')
    op.drop_table('sim_injections')
    # ### end Alembic commands ###
