import {
  ArrowRightLeft,
  Banknote,
  Briefcase,
  Car,
  Clapperboard,
  Coffee,
  Fuel,
  GraduationCap,
  HeartPulse,
  Home,
  Landmark,
  Pill,
  Plane,
  Receipt,
  Repeat,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  TrendingUp,
  UtensilsCrossed,
  Wallet,
  Wifi,
  Zap,
  type LucideIcon,
} from "lucide-react"

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  groceries: ShoppingCart,
  food: UtensilsCrossed,
  food_delivery: UtensilsCrossed,
  dining: UtensilsCrossed,
  chai_canteen: Coffee,
  transport: Car,
  travel: Plane,
  entertainment: Clapperboard,
  utilities: Zap,
  electricity: Zap,
  broadband: Wifi,
  mobile_recharge: Smartphone,
  rent: Home,
  housing: Home,
  salary: Wallet,
  income: Wallet,
  business_inflow: Briefcase,
  gig_payout: Briefcase,
  gst_payment: Landmark,
  shopping: ShoppingBag,
  healthcare: HeartPulse,
  medical: HeartPulse,
  pharmacy: Pill,
  transfer: ArrowRightLeft,
  p2p_transfer: ArrowRightLeft,
  atm: Banknote,
  cash: Banknote,
  cash_withdrawal: Banknote,
  balance_drain: Banknote,
  fuel: Fuel,
  subscription: Repeat,
  card_spend: ShoppingBag,
  education: GraduationCap,
  insurance: Shield,
  investment: TrendingUp,
  fd_interest: TrendingUp,
  emi: Landmark,
  loan: Landmark,
}

/** Maps a transaction/spend category string to a Lucide icon, falling back to a
 * generic receipt for anything not in the map (new sim categories, typos). */
export function categoryIcon(category: string | null | undefined): LucideIcon {
  if (!category) return Receipt
  return CATEGORY_ICONS[category.toLowerCase().replace(/\s+/g, "_")] ?? Receipt
}
